### ISSUE TITLE
Question: Have you notice the edges or you like to set the fix max-width?

### ISSUE THREAD

**Issue by acatzk** [VeoScript/cozy#150]
![Capture](https://user-images.githubusercontent.com/38458781/126872662-9c2d7a20-a7a1-492a-92af-2e15a05279c4.PNG)

**Comment by VeoScript** [comment]
yes, I put max-w-screen in the default layout

![image](https://user-images.githubusercontent.com/26340308/126887264-024b76e6-33da-410d-9b25-b8e80cb50934.png)

![image](https://user-images.githubusercontent.com/26340308/126887182-133a2cef-df48-4e2d-9a26-1803f503543e.png)

**Comment by VeoScript** [comment]
ako nalang alisdan ang max-w-screen size value haha. dako man diay kag screen😅

**Comment by acatzk** [comment]
### Try `control + scroll `para makitag screen size

**Comment by VeoScript** [comment]
> ### Try `control + scroll `para makitag screen size

ako na ning gisuwayan 90% ra ang maximum haha. akong editon ron.
ing ana gihapon ang Login page?

**Comment by acatzk** [comment]
> > ### Try `control + scroll `para makitag screen size
> 
> ako na ning gisuwayan 90% ra ang maximum haha. akong editon ron.
> ing ana gihapon ang Login page?

### ou naka max-width

### TRY OG APPLY ANI

### https://tailwindcss.com/docs/container
```
// tailwind.config.js
module.exports = {
  theme: {
    container: {
      center: true,
    },
  },
}
```

**Comment by VeoScript** [comment]
cge bai akong trabahuon ron salamat
