### ISSUE TITLE
Quick little demo on how to make an awesome Icon commit in your VSCode (Make it your standard)

### ISSUE THREAD

**Issue by acatzk** [VeoScript/cozy#87]
### First: You need to install **`Emoji Commit`** Extension in your VSCode

![1](https://user-images.githubusercontent.com/38458781/125784612-5fb6df8b-101b-4342-b218-37ca5e951cda.PNG)

### Second: Switch/Create your desire branch
![2](https://user-images.githubusercontent.com/38458781/125784963-74b8cf4f-304b-4c95-a8b1-74dcb5ea2353.PNG)

### Third: Go to VSCode `Source Control` or Press (Ctrl+Shift+G) and click this Icon
![3](https://user-images.githubusercontent.com/38458781/125785354-ecc1038c-3dd3-49b7-a8a2-1ad4feb91cb0.PNG)
![image](https://user-images.githubusercontent.com/38458781/125785555-580f9b0f-e881-4922-bdfe-875ce666be4d.png)

### Fourth: You can commit here in VSCode or copy it in your git bash. P.S: First letter must be capital
![4](https://user-images.githubusercontent.com/38458781/125785809-8c4957a3-274b-43b2-8db9-1b033376292b.PNG)
![5](https://user-images.githubusercontent.com/38458781/125785959-b4237273-5aa2-43b2-abd6-756928d438b3.PNG)

**Comment by acatzk** [comment]
### Writing commit messages
Use only the following Git commit messages. The simple and small footprint is the key to Emoji-Logo.

📦 NEW: IMPERATIVE_MESSAGE
Use when you add something entirely new.
      e.g., 📦 NEW: Add Git ignore file

👌 IMPROVE: IMPERATIVE_MESSAGE
Use when you improve/enhance piece of code like refactoring etc.
      e.g., 👌 IMPROVE: Remote IP API Function

🐛 FIX: IMPERATIVE_MESSAGE
Use when you fix a bug. Need I say more?
      e.g., 🐛 FIX: Case converter

📖 DOC: IMPERATIVE_MESSAGE
Use when you add documentation, like README.md or even inline docs.
      e.g., 📖 DOC: API Interface Tutorial

🚀 RELEASE: IMPERATIVE_MESSAGE
Use when you release a new version. 
     e.g., 🚀 RELEASE: Version 2.0.0

✅ TEST: IMPERATIVE_MESSAGE
Use when you release a new version.
     e.g., ✅ TEST: Mock User Login/Logout

**Comment by VeoScript** [comment]
Whoah! I will give it a try
